config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  get "/yaml_preview", to: "yaml_previews#create", as: :yaml_preview
  get "/about", to: "home#about", as: :about

  root "home#show"
end

app/models/accessories_config.rb
# frozen_string_literal: true

class AccessoriesConfig < BaseConfig
  private

  def values
    {
      postgres:
    }
  end

  def defaults
    {}
  end

  def postgres
    return unless @params.dig(:postgres, :enabled)&.to_boolean

    {
      image: @params.dig(:postgres, :image),
      host: @params.dig(:postgres, :host),
      port: @params.dig(:postgres, :port).presence || "5432",
      env: {
        secret: [
          "POSTGRES_USER",
          "POSTGRES_PASSWORD"
        ]
      },
      volumes: [
        "postgres:/var/lib/postgresql/data"
      ]
    }
  end
end

app/models/base_config.rb
# frozen_string_literal: true

class BaseConfig
  def initialize(params = {})
    @params = params
  end

  def to_h
    return if optional? && values.compact.empty?

    defaults.deep_merge(values.compact)
  end

  private

  def values
    raise NotImplementedError.new("This method must be implemented in a subclass")
  end

  def optional?
    false
  end
end

app/models/builder_config.rb
# frozen_string_literal: true

class BuilderConfig < BaseConfig
  private

  def values
    {
      arch:,
      remote:
    }
  end

  def arch
    return if @params[:arch].blank? || @params[:arch] == "default"

    @params[:arch].presence
  end

  def remote
    @params[:remote].presence
  end

  def defaults
    { arch: "default" }
  end

  def optional?
    true
  end
end

app/models/env_config.rb
# frozen_string_literal: true

class EnvConfig < BaseConfig
  private

  def values
    {
      clear:,
      secret:
    }
  end

  def clear
    return if @params[:clear].blank?

    @params[:clear].map do |clear_env|
      {
        "#{clear_env[:key].upcase}": clear_env[:value]
      }
    end
  end

  def secret
    items = @params[:secret]

    items.presence && Array.wrap(items.map(&:upcase).compact_blank)
  end

  def defaults
    { secret: [ "RAILS_MASTER_KEY" ] }
  end
end

app/models/proxy_config.rb
# frozen_string_literal: true

class ProxyConfig < BaseConfig
  private

  def values
    {
      hosts:,
      ssl:,
      app_port:
    }
  end

  def hosts
    hosts = @params[:hosts].presence

    return if hosts.blank?

    hosts = hosts.reject(&:blank?)

    hosts.size == 1 ? hosts.first : hosts
  end

  def ssl
    @params.dig(:ssl, :enabled)&.to_boolean
  end

  def app_port
    return unless @params[:app_port].present?

    @params[:app_port].to_i
  end

  def defaults
    { hosts: "myapp.example.com" }
  end
end

app/models/registry_config.rb
# frozen_string_literal: true

class RegistryConfig < BaseConfig
  private

  def values
    {
      server:,
      username:,
      password:
    }
  end

  def server
    @params[:server].presence
  end

  def username
    @params[:username].presence
  end

  def password
    return unless @params[:password].present?

    [ @params[:password].presence ]
  end

  def defaults
    { username: "registry-user-name", password: [ "KAMAL_REGISTRY_PASSWORD" ] }
  end
end

app/models/servers_config.rb
# frozen_string_literal: true

class ServersConfig < BaseConfig
  private

  def values
    {
      web:,
      jobs:
    }
  end

  def defaults
    { web: "100.100.100.100" }
  end

  def web
    @params[:host].presence
  end

  def jobs
    return unless @params.dig(:jobs, :enabled)&.to_boolean
    return unless @params.dig(:jobs, :host).present?

    jobs = {}
    jobs[:hosts] = @params.dig(:jobs, :host)
    jobs[:cmd] = @params.dig(:jobs, :cmd) if @params.dig(:jobs, :cmd).present?

    jobs
  end
end

app/models/yaml_document.rb
# frozen_string_literal: true

class YamlDocument
  def initialize(params = {})
    @params = params
  end

  def output
    yaml_data = {
      service: @params[:name].presence || "your_service",
      image: @params[:docker_image].presence || "image/your_service",
      servers: ServersConfig.new(@params.fetch(:servers, {})).to_h,
      proxy: ProxyConfig.new(@params.fetch(:proxy, {})).to_h,
      registry: RegistryConfig.new(@params.fetch(:registry, {})).to_h,
      builder: BuilderConfig.new(@params.fetch(:builder, {})).to_h,
      env: EnvConfig.new(@params.fetch(:env, {})).to_h,
      accessories: AccessoriesConfig.new(@params.fetch(:accessories, {})).to_h
    }

    raw_yaml = yaml_data.compact.deep_stringify_keys.to_yaml(indentation: 2)
    adjust_yaml_indentation(raw_yaml)
  end

  private

  def adjust_yaml_indentation(yaml_str, indent_size = 2)
    lines = yaml_str.lines
    adjusted_lines = []
    current_indent = 0

    lines.each do |line|
      if line =~ /^(\s*)([^:\s]+):\s*$/
        # Array key
        current_indent = $1.length + indent_size
        adjusted_lines << line
      elsif line =~ /^(\s*)-\s+/
        # Array element
        adjusted_lines << (" " * current_indent) + line.strip + "\n"
      else
        adjusted_lines << line
      end
    end

    adjusted_lines.join
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about; end

  def show
    @yaml_document = YamlDocument.new
  end
end

app/controllers/yaml_previews_controller.rb
# frozen_string_literal: true

class YamlPreviewsController < ApplicationController
  def create
    @yaml_document = YamlDocument.new(yaml_params)

    respond_to do |format|
      format.html { render :create }
      format.yaml {
        send_data @yaml_document.output,
            filename: "deploy.yml",
            type: "text/yaml",
            disposition: "attachment"
      }
    end
  end

  private

  def yaml_params
    params.permit(
      :name,
      :docker_image,
      builder: [ :arch, :remote ],
      proxy: [ :app_port, { hosts: [], ssl: [ :enabled ] } ],
      registry: [ :server, :username, :password ],
      servers: [ :host, { jobs: [ :enabled, :host, :cmd ] } ],
      env: { clear: [ :key, :value ], secret: [] },
      accessories: {
        postgres: [ :enabled, :host, :image, :port ]
      }
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def navbar_link(name, path)
    active = request.path == path

    link_to name, path, class: class_names('relative block px-3 py-2.5 transition', 'text-orange-600' => active)
  end

  def copy_to_clipboard_btn(text)
    tag.button class: "flex gap-1 items-center text-gray-400 cursor-pointer hover:text-gray-200 relative",
      data: {
        controller: "copy-to-clipboard", action: "copy-to-clipboard#copy",
        copy_to_clipboard_content_value: text
      } do
      concat icon("clipboard", class: "h-4 w-4")
      concat content_tag :span, "Copy"
      concat content_tag :span, "Copied!",
        class: "absolute -top-6 text-xs text-gray-100 opacity-0",
        data: { copy_to_clipboard_target: "message" }
    end
  end

  def download_button
    tag.button "", class: "flex gap-1 items-center text-gray-400 cursor-pointer hover:text-gray-200",
      data: {
        action: "autosubmit#submit",
        autosubmit_format_param: "yaml"
      } do
      concat icon "arrow-down-tray", class: "w-4 h-4"
      concat content_tag :span, "Download"
    end
  end
end

app/views/home/_accessories.html.erb
<fieldset class="divide-y divide-gray-200">
  <legend class="w-full text-2xl font-medium pt-1 pb-4 flex items-center gap-2">
    Accessories
    <%= link_to 'https://kamal-deploy.org/docs/configuration/accessories/', class: 'text-orange-600 hover:text-orange-90', target: '_blank' do %>
      <%= icon "arrow-top-right-on-square", class: "w-4 h-4" %>
    <% end %>
  </legend>

  <div class="space-y-4 py-6">
    <p class="text-sm leading-relaxed text-gray-500">
      Accessories are additional services your app depends on — like PostgreSQL, Redis, or Elasticsearch. Kamal will run each accessory in its own container, on the specified host, and manage them alongside your app. These containers are not exposed to the public; they’re meant to be accessed internally by your app. Accessories can have custom commands, environment variables, and volumes for data persistence.
    </p>

    <%= render 'postgres', f: %>
  </div>
</fieldset>

app/views/home/_builder_fields.html.erb
<fieldset class="divide-y divide-gray-200">
  <legend class="w-full text-2xl font-medium pt-1 pb-4 flex items-center gap-2">
    Builder
    <%= link_to 'https://kamal-deploy.org/docs/configuration/builders/', class: 'text-orange-600 hover:text-orange-90', target: '_blank' do %>
      <%= icon "arrow-top-right-on-square", class: "w-4 h-4" %>
    <% end %>
  </legend>

  <div class="space-y-4 py-6">
    <p class="text-sm leading-relaxed text-gray-500">
      This section defines how your Docker image is built before deployment. You can specify the target architecture (e.g., arm64 or amd64), and choose whether to build the image locally or on a remote server. This helps ensure your app runs correctly on your production hardware and simplifies cross-platform builds.
    </p>

    <div>
      <%= f.label :arch, "Architecture", class: "text-lg font-medium text-gray-900" %>
      <p class="text-sm leading-relaxed text-gray-500">
        The CPU architecture to build your Docker image for, such as amd64 (Intel/AMD) or arm64 (Apple Silicon, newer servers). This ensures the image is compatible with the servers where it will be deployed.
      </p>
      <%= f.select :arch, ["default", "amd64", "arm64"], {}, name: "builder[arch]", class: "bg-white border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" %>
    </div>
  </div>

  <div class="space-y-4 py-6">
      <%= f.label :arch, "Remote", class: "text-lg font-medium text-gray-900" %>
      <p class="text-sm leading-relaxed text-gray-500">
        If enabled, the image will be built on a remote server instead of your local machine. This is useful when your local environment can't build for the target architecture, or when you want to avoid pushing large images over slow networks.
      </p>
      <%= f.text_field :builder_remote,
          name: "builder[remote]",
          placeholder: "ssh://root@100.100.100.100",
          class: "w-full px-4 py-2 border border-gray-300 text-base rounded-lg shadow-sm focus:outline-none focus:ring-1 focus:ring-orange-600 focus:border-orange-200 text-gray-700 placeholder-gray-400"
      %>
  </div>
</fieldset>

app/views/home/_env_fields.html.erb
<fieldset class="divide-y divide-gray-200">
  <legend class="w-full text-2xl font-medium pt-1 pb-4 flex items-center gap-2">
    Environment Variables
    <%= link_to 'https://kamal-deploy.org/docs/configuration/environment-variables/', class: 'text-orange-600 hover:text-orange-90', target: '_blank' do %>
      <%= icon "arrow-top-right-on-square", class: "w-4 h-4" %>
    <% end %>
  </legend>

  <div class="space-y-4 py-6" data-controller="array-input">
    <p class="text-sm leading-relaxed text-gray-500">
      This section defines environment variables that will be available to your application at runtime. Use this to set things like RAILS_ENV, API keys, or any other configuration your app needs. These variables are injected into the running containers, so avoid putting secrets directly here—use secret managers or encrypted variables when possible.
    </p>

    <%= f.label :env_clear, "Clear", class: "text-lg font-medium text-gray-900" %>
    <p class="text-sm leading-relaxed text-gray-500">
      Removes a previously set environment variable from the container’s environment. This is useful if you want to override or clean up a value from a shared config.
    </p>

    <div data-array-input-target="container">
      <template data-array-input-target="template">
        <div class="flex items-center space-x-2 mt-2">
          <%= f.text_field :env_clear_key,
            name: "env[clear][][key]",
            placeholder: "RAILS_SERVE_STATIC_FILES",
            data: { autosubmit_target: 'dynamicInput' },
            class: "uppercase w-full px-4 py-2 border border-gray-300 text-base rounded-lg shadow-sm focus:outline-none focus:ring-1 focus:ring-orange-600 focus:border-orange-200 text-gray-700 placeholder-gray-400"
          %>
          <%= f.text_field :env_clear_value,
            name: "env[clear][][value]",
            placeholder: "true",
            data: { autosubmit_target: 'dynamicInput' },
            class: "w-full px-4 py-2 border border-gray-300 text-base rounded-lg shadow-sm focus:outline-none focus:ring-1 focus:ring-orange-600 focus:border-orange-200 text-gray-700 placeholder-gray-400"
          %>
          <button type="button" data-action="click->array-input#remove" class="text-sm font-semibold p-2 rounded-full text-black/70 cursor-pointer hover:bg-gray-200 active:bg-gray-300">
            <%= icon "x-mark", class: ["h-4", "w-4"] %>
          </button>
        </div>
      </template>
    </div>

    <div class="mt-2">
      <button type="button" data-action="click->array-input#add" class="text-sm font-semibold flex gap-1 items-center py-2 px-4 rounded-xl shadow-sm text-white cursor-pointer bg-black/80 hover:bg-black active:bg-black">
        <%= icon "plus", class: "w-4 h-4 text-white" %>
        Add variable
      </button>
    </div>
  </div>

  <div class="space-y-4 py-6" data-controller="array-input">
    <%= f.label :env_secret, "Secret", class: "text-lg font-medium text-gray-900" %>
    <p class="text-sm leading-relaxed text-gray-500">
      Marks an environment variable as sensitive. Kamal will load its value from the host machine’s environment at runtime instead of hardcoding it into the deploy file. This keeps secrets like API keys or database passwords out of version control.
    </p>

    <div data-array-input-target="container">
      <template data-array-input-target="template">
        <div class="flex items-center space-x-2 mt-2">
          <%= f.text_field :env_secret,
            name: "env[secret][]",
            placeholder: "Enter an environment variable",
            data: { autosubmit_target: 'dynamicInput' },
            class: "uppercase w-full px-4 py-2 border border-gray-300 text-base rounded-lg shadow-sm focus:outline-none focus:ring-1 focus:ring-orange-600 focus:border-orange-200 text-gray-700 placeholder-gray-400"
          %>
          <button type="button" data-action="click->array-input#remove" class="text-sm font-semibold p-2 rounded-full text-black/70 cursor-pointer hover:bg-gray-200 active:bg-gray-300">
            <%= icon "x-mark", class: ["h-4", "w-4"] %>
          </button>
        </div>
      </template>
    </div>

    <div class="mt-2">
      <button type="button" data-action="click->array-input#add" class="text-sm font-semibold flex gap-1 items-center py-2 px-4 rounded-xl shadow-sm text-white cursor-pointer bg-black/80 hover:bg-black active:bg-black">
        <%= icon "plus", class: "w-4 h-4 text-white" %>
        Add variable
      </button>
    </div>
  </div>
</fieldset>

app/views/home/_form.html.erb
<%= form_with url: yaml_preview_path, method: :get,
    data: { autosubmit_target: 'form', action: "input->autosubmit#submit", turbo_frame: "yaml_preview" },
    html: { autocomplete: "off" } do |f|
%>
  <input type="hidden" name="format" data-autosubmit-target="format" value="html">

  <div class="flex flex-col gap-10">
    <%= render 'overview', f: %>
    <%= render 'server_fields', f: %>
    <%= render 'proxy_fields', f: %>
    <%= render 'builder_fields', f: %>
    <%= render 'registry_fields', f: %>
    <%= render 'env_fields', f: %>
    <%= render 'accessories', f: %>
    <%= render 'privacy' %>
  </div>
<% end %>

app/views/home/_overview.html.erb
<fieldset class="divide-y divide-gray-200">
  <legend class="w-full text-2xl font-medium pt-1 pb-4 flex items-center gap-2">
    Overview
    <%= link_to 'https://kamal-deploy.org/docs/configuration/overview/', class: 'text-orange-600 hover:text-orange-90', target: '_blank' do %>
      <%= icon "arrow-top-right-on-square", class: "w-4 h-4" %>
    <% end %>
  </legend>

  <div class="space-y-4 py-6">
    <%= f.label :name, "Service name", class: "text-lg font-medium text-gray-900" %>
    <p class="text-sm leading-relaxed text-gray-500">
      A short, unique name for your app or service. This name is used to label containers, logs, and other resources, so keep it lowercase and simple (e.g., myapp). It becomes part of hostnames like myapp-web-1.
    </p>
    <%= f.text_field :name,
      placeholder: "your_service",
      class: "w-full px-4 py-2 border border-gray-300 text-base rounded-lg shadow-sm focus:outline-none focus:ring-1 focus:ring-orange-600 focus:border-orange-200 text-gray-700 placeholder-gray-400" %>
  </div>

  <div class="space-y-4 py-6">
    <%= f.label :docker_image, "Docker image name", class: "text-lg font-medium text-gray-900" %>
    <p class="text-sm leading-relaxed text-gray-500">
      It defines both the repository name and tag for your Docker image. For example, it might be something like "mycompany/myapp:latest" or "username/application:v1.2.3".
This name needs to be unique and must be available in the Docker registry that Kamal has access to (such as Docker Hub, GitHub Container Registry, or a private registry you've configured).
    </p>
    <%= f.text_field :docker_image,
      placeholder: "image/your_service",
      class: "w-full px-4 py-2 border border-gray-300 text-base rounded-lg shadow-sm focus:outline-none focus:ring-1 focus:ring-orange-600 focus:border-orange-200 text-gray-700 placeholder-gray-400" %>
  </div>
</fieldset>

app/views/home/_postgres.html.erb
<div class="space-y-4 py-6">
  <div data-controller="toggler">
    <div class="flex items-center gap-2 mt-2">
      <label class="switch">
        <%= f.check_box :postgres_enabled, name: "accessories[postgres][enabled]",
          data: { action: "toggler#toggle" },
          class: "h-5 w-5 text-indigo-600 border-gray-300 rounded focus:ring-indigo-500" %>
        <span class="slider round"></span>
      </label>
      <%= f.label :postgres_enabled, "Include a PostgreSQL accessory", class: "text-sm font-semibold text-gray-700" %>
    </div>

    <div class="mt-4 space-y-3 hidden" data-toggler-target="target">
      <div>
        <%= f.label :postgres_image, "Image", class: "text-sm font-medium text-gray-900" %>
        <p class="text-sm leading-relaxed text-gray-500">
          The Docker image to use for the accessory. For PostgreSQL, this might be something like postgres:15-alpine. Make sure the image version matches what your app expects.
        </p>
        <%= f.text_field :postgres_image,
          name: "accessories[postgres][image]",
          placeholder: "postgres:16.3",
          class: "w-full px-4 py-2 border border-gray-300 text-base rounded-lg shadow-sm focus:outline-none focus:ring-1 focus:ring-orange-300 focus:border-orange-300 text-gray-700 placeholder-gray-400" %>
      </div>

      <div>
        <%= f.label :postgres_host, "Host", class: "text-sm font-medium text-gray-900" %>
        <p class="text-sm leading-relaxed text-gray-500">
          The server where this accessory container will run. It should be a machine reachable by your app containers (often the same server or within the same network). Kamal will deploy the accessory here and manage its lifecycle.
        </p>
        <%= f.text_field :postgres_host,
          name: "accessories[postgres][host]",
          placeholder: "100.100.100.100",
          class: "w-full px-4 py-2 border border-gray-300 text-base rounded-lg shadow-sm focus:outline-none focus:ring-1 focus:ring-orange-300 focus:border-orange-300 text-gray-700 placeholder-gray-400" %>
      </div>

      <div>
        <%= f.label :postgres_port, "Port", class: "text-sm font-medium text-gray-900" %>
        <p class="text-sm leading-relaxed text-gray-500">
          The port inside the container where PostgreSQL will listen (default is 5432). This is used for internal communication between your app and the database. You usually don’t need to change it unless you have a specific reason.
        </p>
        <%= f.text_field :postgres_host,
          name: "accessories[postgres][port]",
          placeholder: "5432",
          class: "w-full px-4 py-2 border border-gray-300 text-base rounded-lg shadow-sm focus:outline-none focus:ring-1 focus:ring-orange-300 focus:border-orange-300 text-gray-700 placeholder-gray-400" %>
      </div>
    </div>
  </div>
</div>

app/views/home/_privacy.html.erb
<h2 class="w-full border-b border-gray-200 text-2xl font-medium pt-1 pb-4">
  Your privacy matters
</h2>

<p class="text-sm leading-relaxed text-gray-500">
  We don’t store any of the data you enter. It’s only used to generate your config file and never touches a database.
</p>

app/views/home/_registry_fields.html.erb
<fieldset class="divide-y divide-gray-200">
  <legend class="w-full text-2xl font-medium pt-1 pb-4 flex items-center gap-2">
    Registry
    <%= link_to 'https://kamal-deploy.org/docs/configuration/docker-registry/', class: 'text-orange-600 hover:text-orange-90', target: '_blank' do %>
      <%= icon "arrow-top-right-on-square", class: "w-4 h-4" %>
    <% end %>
  </legend>

  <div class="space-y-4 py-6">
    <p class="text-sm leading-relaxed text-gray-500">
      This section tells Kamal where to push your Docker image so it can be pulled by your servers during deployment. You can use a service like Docker Hub, GitHub Container Registry, or any private registry. Credentials are stored securely using environment variables.
    </p>

    <%= f.label :registry_server, "Server", class: "text-lg font-medium text-gray-900" %>
    <p class="text-sm leading-relaxed text-gray-500">
      The URL of your container registry (e.g., ghcr.io, index.docker.io for Docker Hub, or your own private registry domain). Kamal will push the image here so servers can pull it.
    </p>
    <%= f.text_field :registry_server,
      name: "registry[server]",
      autocomplete: "off",
      placeholder: "registry.mydomain.com",
      class: "w-full px-4 py-2 border border-gray-300 text-base rounded-lg shadow-sm focus:outline-none focus:ring-1 focus:ring-orange-600 focus:border-orange-200 text-gray-700 placeholder-gray-400" %>
  </div>

  <div class="space-y-4 py-6">
    <%= f.label :registry_username, "Username", class: "text-lg font-medium text-gray-900" %>
    <p class="text-sm leading-relaxed text-gray-500">
      The username used to log in to your container registry. This is usually your Docker Hub or GitHub username.
    </p>
    <%= f.text_field :registry_username,
      name: "registry[username]",
      autocomplete: "off",
      placeholder: "Enter registry username",
      class: "w-full px-4 py-2 border border-gray-300 text-base rounded-lg shadow-sm focus:outline-none focus:ring-1 focus:ring-orange-600 focus:border-orange-200 text-gray-700 placeholder-gray-400" %>
  </div>

  <div class="space-y-4 py-6">
    <%= f.label :registry_password, "Password env var name", class: "text-lg font-medium text-gray-900" %>
    <p class="text-sm leading-relaxed text-gray-500">
      The name of the environment variable that holds your registry password or access token (e.g., REGISTRY_PASSWORD). Kamal uses this to authenticate when pushing and pulling images.
    </p>
    <%= f.text_field :registry_password,
      name: "registry[password]",
      placeholder: "Enter registry password env var name",
      autocomplete: "off",
      class: "w-full px-4 py-2 border border-gray-300 text-base rounded-lg shadow-sm focus:outline-none focus:ring-1 focus:ring-orange-600 focus:border-orange-200 text-gray-700 placeholder-gray-400" %>
  </div>
</fieldset>

app/views/home/show.html.erb
<div data-controller="autosubmit" class="md:h-[calc(100vh-8rem)] md:grid md:grid-cols-2">
  <div class="px-6 py-4 md:px-16 md:py-10 bg-white rounded-lg shadow-lg m-6 mb-0 md:h-full relative md:overflow-auto scrollbar-hidden">
    <h2 class="text-2xl font-bold">
      Let's kamalify your app!
    </h2>
    <p class="text-sm leading-relaxed text-gray-500 mb-8">
      Fill the form below to generate a Kamal configuration file for your application.
    </p>

    <%= render 'form' %>
  </div>

  <!--<div class="px-6 py-4 md:px-16 md:py-10 bg-[#282c34] rounded-lg shadow-lg m-6 md:h-full relative md:overflow-auto">-->
  <%= turbo_frame_tag "yaml_preview", src: yaml_preview_path, loading: :lazy, class: 'py-4 md:py-10 bg-[#282c34] rounded-lg shadow-lg m-3 md:m-6 md:h-full relative md:overflow-auto scrollbar-hidden' %>
  <!--</div>-->
</div>

<p class="w-full text-center md:w-fit md:absolute md:bottom-4 md:right-6 text-xs md:flex md:items-center">
  <span> Made with ❤️ by <a href="https://unagisoftware.com" target="_blank" class="text-[#ff5e2c]">Unagi</a> </span>
</p>

app/views/layouts/_navbar.html.erb
<nav class="relative">
  <header class="w-full pointer-events-none relative z-50 flex flex-col">
    <div class="top-0 z-10 md:h-16 pt-2">
      <div class="relative px-4 sm:px-8 lg:px-12">
        <div class="">
          <div class="relative flex items-center gap-4 justify-center">
            <div class="flex flex-1">
              <a href="/" aria-label="" title="" class="block pointer-events-auto">
                <%= icon "rocket-launch", class: "h-10 w-10 text-orange-600" %>
              </a>
            </div>
            <div class="flex flex-1 justify-center">
              <nav class="pointer-events-auto md:block">
                <ul class="flex rounded-full bg-white/90 px-3 text-sm font-medium text-gray-800 shadow-lg shadow-gray-800/5 ring-1 ring-gray-900/5 backdrop-blur">
                  <li> <%= navbar_link "Home", root_path %> </li>
                  <li> <%= navbar_link "About", about_path %> </li>
                </ul>
              </nav>

            </div>
            <div class="flex justify-end flex-1">
              <div class="pointer-events-auto">
                <a href="https://github.com/unagisoftware/kamalify" title="GitHub" target="blank" aria-label="GitHub" class="block group rounded-full bg-white/90 px-3.5 py-2.5 shadow-lg shadow-gray-800/5 ring-1 ring-gray-900/5 backdrop-blur">
                  <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" class="h-5 w-5 text-gray-500 group-hover:text-gray-800" viewBox="0 0 30 30">
                    <path d="M15,3C8.373,3,3,8.373,3,15c0,5.623,3.872,10.328,9.092,11.63C12.036,26.468,12,26.28,12,26.047v-2.051 c-0.487,0-1.303,0-1.508,0c-0.821,0-1.551-0.353-1.905-1.009c-0.393-0.729-0.461-1.844-1.435-2.526 c-0.289-0.227-0.069-0.486,0.264-0.451c0.615,0.174,1.125,0.596,1.605,1.222c0.478,0.627,0.703,0.769,1.596,0.769 c0.433,0,1.081-0.025,1.691-0.121c0.328-0.833,0.895-1.6,1.588-1.962c-3.996-0.411-5.903-2.399-5.903-5.098 c0-1.162,0.495-2.286,1.336-3.233C9.053,10.647,8.706,8.73,9.435,8c1.798,0,2.885,1.166,3.146,1.481C13.477,9.174,14.461,9,15.495,9 c1.036,0,2.024,0.174,2.922,0.483C18.675,9.17,19.763,8,21.565,8c0.732,0.731,0.381,2.656,0.102,3.594 c0.836,0.945,1.328,2.066,1.328,3.226c0,2.697-1.904,4.684-5.894,5.097C18.199,20.49,19,22.1,19,23.313v2.734 c0,0.104-0.023,0.179-0.035,0.268C23.641,24.676,27,20.236,27,15C27,8.373,21.627,3,15,3z"></path>
                  </svg>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
</nav>